"""This module contains the gameplay settings"""

WARRIOR = "1"
ROBBER = "2"
WIZARD = "3"

INITIAL_PLAYERS_HEALTH = 5
SCORE_FOR_SUCCESS = 1
STEP_SCORE = 1
SCORE_FOR_DEFETING_THE_ENEMY = 5
ENEMY_HEALTH_DOWN = 1

FILENAME = "scores.txt"
FILE_ENCODING = "Windows-1251"

SUCCESS_ATTACK = "YOUR ATTACK IS SUCCESSFUL!"
FAILURE_ATTACK = "YOUR ATTACK IS FAILED!"
DRAW_MSG = "IT'S A DRAW!"
SUCCESS_DEFENCE = "YOUR DEFENCE IS SUCCESSFUL!"
FAILURE_DEFENCE = "YOUR DEFENCE IS FAILED!"

SUCCESS = 1
FAILURE = -1
DRAW = 0

MSG_ENEMYDOWN = "WOW!"
MSG_GAMEOVER = " GAME OVER!"
